#!/bin/bash -e

ROOT=/var/fauxroku
APP=$1
HASH=$2

APP_DIR=$ROOT/apps/$APP
CACHE_DIR=$APP_DIR/cache
BUILD_DIR=$APP_DIR/build/$HASH
SLUG_DIR=$APP_DIR/slug

export GIT_DIR=$HOME/$APP.git
export GIT_WORK_TREE=$BUILD_DIR

mkdir -p $BUILD_DIR
mkdir -p $CACHE_DIR
mkdir -p $SLUG_DIR

echo "-----> Received push, deploying revision $HASH"

echo "-----> Checking out new code to $BUILD_DIR"
git checkout -fq $HASH

cd $ROOT/buildpacks

echo "-----> Detecting build type"
for BP in *
do cd $ROOT/buildpacks/$BP
bin/detect $BUILD_DIR || continue
bin/compile $BUILD_DIR $CACHE_DIR
bin/release $BUILD_DIR > $BUILD_DIR/.release
break
done

cd $BUILD_DIR
touch $APP_DIR/config
sudo foreman export upstart $SLUG_DIR/init -u root -a $APP -t $ROOT/deploy/upstart -l $SLUG_DIR/log -e $APP_DIR/config
cp -r $BUILD_DIR $SLUG_DIR/code
